// Banco de perguntas. A primeira alternativa de cada pergunta é a correta
// (o site embaralha na hora de mostrar).
//
// tipo: "atribuicao" (conceitual, duradouro) | "real" (caso recente, com fonte e data)
// nivel: "federal" | "estadual" | "municipal"
// revisar: true = precisa de conferência humana antes de confiar
const TEMAS = {
  "processo-legislativo": "Processo legislativo e atos",
  "executivo": "Poder Executivo",
  "controle": "Controle e fiscalização",
  "orcamento": "Orçamento e tributos",
  "competencias": "Competência para legislar",
  "cargos": "Cargos e mandatos",
  "educacao": "Educação",
  "habitacao": "Habitação e urbanismo",
  "saude": "Saúde",
  "justica": "Justiça e Ministério Público",
  "seguranca": "Segurança pública",
  "servicos": "Serviços públicos locais",
  "economia": "Economia e moeda",
};

// Quando uma alternativa é exatamente um destes órgãos, o site mostra
// entre parênteses quem o compõe.
const ORGAOS = {
  "Congresso Nacional": "deputados federais e senadores",
  "Câmara dos Deputados": "deputados federais",
  "Senado Federal": "senadores",
  "Assembleia Legislativa": "deputados estaduais",
  "Câmara Municipal": "vereadores",
  "Supremo Tribunal Federal": "ministros do STF",
  "Tribunal de Contas da União": "ministros do TCU",
  "Tribunal de Contas": "conselheiros",
  "Superior Tribunal de Justiça": "ministros do STJ",
  "Tribunal Superior Eleitoral": "ministros do TSE",
  "Ministério Público": "promotores e procuradores",
  "Conselho Nacional de Justiça": "conselheiros",
  "Conselho Nacional do Ministério Público": "conselheiros",
  "Copom": "Comitê de Política Monetária: presidente e diretores do Banco Central",
  "Tribunal de Justiça": "desembargadores",
};

const QUESTIONS = [
  // ---------- Federal: atribuições gerais ----------
  {
    id: "q001", tema: "processo-legislativo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem sanciona ou veta um projeto de lei aprovado pelo Congresso Nacional?",
    alternativas: ["Presidente da República", "Presidente do Senado", "Ministro da Casa Civil", "Presidente do STF"],
    explicacao: "O projeto aprovado pelo Congresso vai ao Presidente da República, que tem 15 dias úteis para sancioná-lo (total ou parcialmente) ou vetá-lo.",
    fonte: "CF/88, art. 66",
  },
  {
    id: "q002", tema: "processo-legislativo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem analisa um veto presidencial e decide mantê-lo ou derrubá-lo?",
    alternativas: ["Congresso Nacional", "Presidente da República", "Supremo Tribunal Federal", "Câmara dos Deputados"],
    explicacao: "O veto é apreciado pelo Congresso Nacional em sessão conjunta de deputados e senadores. Para derrubá-lo é preciso maioria absoluta dos deputados e dos senadores.",
    fonte: "CF/88, art. 66, §§ 4º e 5º",
  },
  {
    id: "q003", tema: "processo-legislativo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem pode editar uma medida provisória, com força de lei, em caso de relevância e urgência?",
    alternativas: ["Presidente da República", "Câmara dos Deputados", "Senado Federal", "Ministro da Fazenda"],
    explicacao: "A medida provisória é ato do Presidente da República e vale imediatamente, mas precisa ser votada pelo Congresso em até 120 dias para não perder a eficácia.",
    fonte: "CF/88, art. 62",
  },
  {
    id: "q004", tema: "controle", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem julga o Presidente da República por crime de responsabilidade (impeachment)?",
    alternativas: ["Senado Federal", "Câmara dos Deputados", "Supremo Tribunal Federal", "Congresso Nacional"],
    explicacao: "O julgamento é do Senado Federal, presidido pelo Presidente do STF. Já crimes comuns são julgados pelo STF.",
    fonte: "CF/88, art. 52, I e parágrafo único",
  },
  {
    id: "q005", tema: "controle", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem autoriza, por 2/3 dos votos, a abertura de processo contra o Presidente da República?",
    alternativas: ["Câmara dos Deputados", "Senado Federal", "Supremo Tribunal Federal", "Procurador-Geral da República"],
    explicacao: "A Câmara dos Deputados admite a acusação por 2/3 dos votos. Só então o caso segue para julgamento no Senado (crime de responsabilidade) ou no STF (crime comum).",
    fonte: "CF/88, arts. 51, I, e 86",
  },
  {
    id: "q006", tema: "controle", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem aprova, por maioria absoluta, a escolha de um ministro do STF indicado pelo Presidente?",
    alternativas: ["Senado Federal", "Câmara dos Deputados", "Congresso Nacional", "Presidente do STF"],
    explicacao: "O Presidente indica, o Senado aprova a indicação por maioria absoluta depois de sabatina, e então o Presidente nomeia.",
    fonte: "CF/88, arts. 101, parágrafo único, e 52, III, a",
  },
  {
    id: "q007", tema: "executivo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem decreta intervenção federal em um estado?",
    alternativas: ["Presidente da República", "Congresso Nacional", "Supremo Tribunal Federal", "Ministro da Defesa"],
    explicacao: "A intervenção é decretada pelo Presidente da República, por iniciativa própria ou após requisição ou provimento do Judiciário, conforme o caso.",
    fonte: "CF/88, arts. 34 e 84, X",
  },
  {
    id: "q008", tema: "executivo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem tem competência para conceder indulto a condenados?",
    alternativas: ["Presidente da República", "Supremo Tribunal Federal", "Senado Federal", "Ministro da Justiça"],
    explicacao: "Conceder indulto e comutar penas é atribuição privativa do Presidente da República, que pode delegá-la a ministros, ao PGR ou ao AGU.",
    fonte: "CF/88, art. 84, XII e parágrafo único",
  },
  {
    id: "q009", tema: "executivo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem decreta o estado de sítio, depois das devidas autorizações?",
    alternativas: ["Presidente da República", "Congresso Nacional", "Supremo Tribunal Federal", "Ministro da Defesa"],
    explicacao: "O Presidente ouve o Conselho da República e o Conselho de Defesa Nacional e solicita autorização ao Congresso Nacional (Câmara e Senado, que decidem por maioria absoluta). Autorizado, é o próprio Presidente quem decreta o estado de sítio.",
    fonte: "CF/88, arts. 137 e 84, IX",
  },
  {
    id: "q010", tema: "executivo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem edita decretos para regulamentar a execução de uma lei federal?",
    alternativas: ["Presidente da República", "Ministro de Estado", "Congresso Nacional", "Supremo Tribunal Federal"],
    explicacao: "Expedir decretos e regulamentos para a fiel execução das leis é atribuição privativa do Presidente da República.",
    fonte: "CF/88, art. 84, IV",
  },
  {
    id: "q011", tema: "executivo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem declara guerra, no caso de agressão estrangeira?",
    alternativas: ["Presidente da República", "Ministro da Defesa", "Senado Federal", "Comandante do Exército"],
    explicacao: "O Presidente da República declara guerra no caso de agressão estrangeira, sempre autorizado ou referendado pelo Congresso Nacional.",
    fonte: "CF/88, art. 84, XIX",
  },
  {
    id: "q012", tema: "cargos", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem nomeia o Procurador-Geral da República?",
    alternativas: ["Presidente da República", "Senado Federal", "Supremo Tribunal Federal", "Câmara dos Deputados"],
    explicacao: "O PGR é nomeado pelo Presidente entre integrantes da carreira, mas só depois de o Senado aprovar o nome por maioria absoluta.",
    fonte: "CF/88, art. 128, § 1º",
  },
  {
    id: "q013", tema: "cargos", nivel: "federal", tipo: "atribuicao",
    pergunta: "Qual cargo eletivo tem mandato de 8 anos?",
    alternativas: ["Senador", "Deputado Federal", "Presidente da República", "Vereador"],
    explicacao: "Senadores têm mandato de 8 anos, com renovação de 1/3 e 2/3 do Senado alternadamente a cada 4 anos. Os demais cargos eletivos têm mandato de 4 anos.",
    fonte: "CF/88, art. 46, § 1º",
  },
  {
    id: "q014", tema: "orcamento", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem envia ao Congresso Nacional o projeto de lei do orçamento anual da União?",
    alternativas: ["Presidente da República", "Câmara dos Deputados", "Tribunal de Contas da União", "Presidente do Senado"],
    explicacao: "A iniciativa das leis do ciclo orçamentário (PPA, LDO e LOA) é do chefe do Executivo. O Congresso discute, emenda e aprova.",
    fonte: "CF/88, arts. 84, XXIII, e 165",
  },
  {
    id: "q015", tema: "controle", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem julga anualmente as contas do Presidente da República?",
    alternativas: ["Congresso Nacional", "Tribunal de Contas da União", "Supremo Tribunal Federal", "Senado Federal"],
    explicacao: "O TCU apenas emite um parecer prévio. Quem julga as contas do Presidente é o Congresso Nacional.",
    fonte: "CF/88, arts. 49, IX, e 71, I",
  },
  {
    id: "q016", tema: "competencias", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem tem competência privativa para legislar sobre trânsito e transporte?",
    alternativas: ["Congresso Nacional", "Assembleia Legislativa", "Câmara Municipal", "Prefeito"],
    explicacao: "Legislar sobre trânsito e transporte é competência privativa da União, exercida pelo Congresso Nacional (como no Código de Trânsito Brasileiro). Municípios cuidam da execução local, como sinalização e fiscalização.",
    fonte: "CF/88, art. 22, XI",
  },
  {
    id: "q017", tema: "educacao", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem legisla sobre as diretrizes e bases da educação nacional?",
    alternativas: ["Congresso Nacional", "Ministro da Educação", "Governador", "Prefeito"],
    explicacao: "As diretrizes e bases da educação nacional são competência privativa da União, por lei federal (hoje, a Lei 9.394/1996, a LDB). O Ministro executa e regulamenta, mas não cria a lei.",
    fonte: "CF/88, art. 22, XXIV",
  },

  // ---------- Estadual ----------
  {
    id: "q018", tema: "processo-legislativo", nivel: "estadual", tipo: "atribuicao",
    pergunta: "Quem sanciona ou veta um projeto de lei aprovado pela Assembleia Legislativa?",
    alternativas: ["Governador", "Deputado Estadual", "Presidente da República", "Secretário de Estado"],
    explicacao: "O processo legislativo estadual segue, por simetria, o federal: a Assembleia aprova e o Governador sanciona ou veta.",
    fonte: "CF/88, arts. 25 e 66 (por simetria)",
  },
  {
    id: "q019", tema: "processo-legislativo", nivel: "estadual", tipo: "atribuicao",
    pergunta: "Quem tem iniciativa exclusiva para propor lei que aumenta a remuneração de servidores do Executivo estadual?",
    alternativas: ["Governador", "Deputado Estadual", "Assembleia Legislativa", "Prefeito"],
    explicacao: "Leis sobre o regime e a remuneração dos servidores do Executivo são de iniciativa privativa do chefe do Executivo. Um deputado não pode propô-las.",
    fonte: "CF/88, art. 61, § 1º, II, a (por simetria)",
  },
  {
    id: "q020", tema: "processo-legislativo", nivel: "estadual", tipo: "atribuicao",
    pergunta: "Quem elabora e aprova a Constituição de um estado e as suas emendas?",
    alternativas: ["Assembleia Legislativa", "Governador", "Congresso Nacional", "Tribunal de Justiça"],
    explicacao: "Cada estado se organiza por sua Constituição, elaborada pela Assembleia Legislativa, respeitando os princípios da Constituição Federal.",
    fonte: "CF/88, art. 25 e ADCT, art. 11",
  },

  // ---------- Municipal ----------
  {
    id: "q021", tema: "processo-legislativo", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem sanciona ou veta um projeto de lei aprovado pela Câmara Municipal?",
    alternativas: ["Prefeito", "Vereador", "Governador", "Secretário municipal"],
    explicacao: "Como nos outros níveis, o Legislativo aprova e o chefe do Executivo, aqui o Prefeito, sanciona ou veta.",
    fonte: "CF/88, arts. 29 e 66 (por simetria)",
  },
  {
    id: "q022", tema: "processo-legislativo", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem vota e aprova a Lei Orgânica do município?",
    alternativas: ["Câmara Municipal", "Prefeito", "Assembleia Legislativa", "Tribunal de Contas"],
    explicacao: "A Lei Orgânica, a \"constituição\" do município, é votada em dois turnos pela Câmara Municipal e aprovada por 2/3 dos vereadores. O Prefeito não a sanciona.",
    fonte: "CF/88, art. 29, caput",
  },
  {
    id: "q023", tema: "controle", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem julga as contas anuais do Prefeito?",
    alternativas: ["Câmara Municipal", "Tribunal de Contas", "Governador", "Juiz eleitoral"],
    explicacao: "O Tribunal de Contas emite apenas parecer prévio, que só deixa de prevalecer por voto de 2/3 dos vereadores. O julgamento é da Câmara Municipal.",
    fonte: "CF/88, art. 31, §§ 1º e 2º",
  },
  {
    id: "q024", tema: "habitacao", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem aprova o plano diretor da cidade?",
    alternativas: ["Câmara Municipal", "Prefeito", "Governador", "Assembleia Legislativa"],
    explicacao: "O plano diretor é aprovado pela Câmara Municipal e é obrigatório para cidades com mais de 20 mil habitantes. É o instrumento básico da política de desenvolvimento urbano.",
    fonte: "CF/88, art. 182, § 1º",
  },
  {
    id: "q025", tema: "orcamento", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem aprova a lei que cria ou altera o IPTU?",
    alternativas: ["Câmara Municipal", "Prefeito (por decreto)", "Governador", "Congresso Nacional"],
    explicacao: "Tributo só pode ser criado ou aumentado por lei. O IPTU é imposto municipal, então a lei é aprovada pela Câmara Municipal e sancionada pelo Prefeito.",
    fonte: "CF/88, arts. 150, I, e 156, I",
  },
  {
    id: "q026", tema: "cargos", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem fixa o subsídio dos vereadores para a legislatura seguinte?",
    alternativas: ["Câmara Municipal", "Prefeito", "Tribunal de Contas", "Assembleia Legislativa"],
    explicacao: "O subsídio dos vereadores é fixado pela própria Câmara Municipal, em cada legislatura para a seguinte, respeitados os limites constitucionais.",
    fonte: "CF/88, art. 29, VI",
  },
  {
    id: "q027", tema: "executivo", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem nomeia os secretários municipais?",
    alternativas: ["Prefeito", "Câmara Municipal", "Governador", "Vereador mais votado"],
    explicacao: "Os secretários são auxiliares de confiança do chefe do Executivo e são nomeados e exonerados livremente pelo Prefeito, conforme a Lei Orgânica de cada município.",
    fonte: "Lei Orgânica municipal; CF/88, art. 84, I (por simetria)",
  },
  {
    id: "q028", tema: "competencias", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem legisla sobre assuntos de interesse local, como o horário de funcionamento do comércio?",
    alternativas: ["Câmara Municipal", "Assembleia Legislativa", "Congresso Nacional", "Prefeito (por decreto)"],
    explicacao: "O município legisla sobre assuntos de interesse local, e o STF fixou que o horário de funcionamento de estabelecimentos comerciais é um deles. A lei é da Câmara Municipal.",
    fonte: "CF/88, art. 30, I; Súmula Vinculante 38 do STF",
  },

  // ---------- Lote 2: atribuições gerais (resposta eletiva) ----------
  {
    id: "q029", tema: "cargos", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem preside a Mesa do Congresso Nacional?",
    alternativas: ["Presidente do Senado Federal", "Presidente da Câmara dos Deputados", "Presidente do STF", "Vice-Presidente da República"],
    explicacao: "A Mesa do Congresso Nacional é presidida pelo Presidente do Senado Federal. Os demais cargos da Mesa são ocupados alternadamente por membros da Câmara e do Senado.",
    fonte: "CF/88, art. 57, § 5º",
  },
  {
    id: "q030", tema: "executivo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem assume a Presidência da República quando o Presidente está impedido ou o cargo fica vago?",
    alternativas: ["Vice-Presidente da República", "Presidente da Câmara dos Deputados", "Presidente do Senado Federal", "Presidente do STF"],
    explicacao: "O Vice-Presidente substitui o Presidente nos impedimentos e o sucede se o cargo vagar. Se o Vice também faltar, são chamados, nesta ordem, o Presidente da Câmara, o do Senado e o do STF.",
    fonte: "CF/88, arts. 79 e 80",
  },
  {
    id: "q031", tema: "processo-legislativo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem promulga uma emenda à Constituição Federal?",
    alternativas: ["Mesas da Câmara dos Deputados e do Senado Federal", "Presidente da República", "Supremo Tribunal Federal", "Ministro da Justiça"],
    explicacao: "Emenda constitucional não passa por sanção nem veto presidencial. Ela é promulgada pelas Mesas da Câmara dos Deputados e do Senado Federal, com número de ordem.",
    fonte: "CF/88, art. 60, § 3º",
  },
  {
    id: "q032", tema: "processo-legislativo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem tem competência para convocar um plebiscito nacional?",
    alternativas: ["Congresso Nacional", "Presidente da República", "Tribunal Superior Eleitoral", "Supremo Tribunal Federal"],
    explicacao: "Cabe ao Congresso Nacional autorizar referendo e convocar plebiscito, por decreto legislativo. A Justiça Eleitoral apenas organiza a votação.",
    fonte: "CF/88, art. 49, XV; Lei 9.709/1998",
  },
  {
    id: "q033", tema: "cargos", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem fixa o subsídio do Presidente da República, do Vice-Presidente e dos Ministros de Estado?",
    alternativas: ["Congresso Nacional", "Supremo Tribunal Federal", "Ministro da Fazenda", "Tribunal de Contas da União"],
    explicacao: "O subsídio dessas autoridades é fixado pelo Congresso Nacional. O Presidente não decide o próprio salário.",
    fonte: "CF/88, art. 49, VIII",
  },
  {
    id: "q034", tema: "executivo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem celebra tratados internacionais em nome do Brasil?",
    alternativas: ["Presidente da República", "Congresso Nacional", "Ministro das Relações Exteriores", "Senado Federal"],
    explicacao: "O Presidente da República celebra tratados, convenções e atos internacionais, mas eles só valem depois de aprovados pelo Congresso Nacional, por decreto legislativo.",
    fonte: "CF/88, arts. 84, VIII, e 49, I",
  },
  {
    id: "q035", tema: "executivo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem exerce o comando supremo das Forças Armadas?",
    alternativas: ["Presidente da República", "Ministro da Defesa", "Congresso Nacional", "Comandante do Exército"],
    explicacao: "As Forças Armadas estão sob a autoridade suprema do Presidente da República. O Ministro da Defesa e os comandantes são subordinados a ele.",
    fonte: "CF/88, arts. 84, XIII, e 142",
  },
  {
    id: "q036", tema: "executivo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem nomeia e exonera livremente os ministros de Estado?",
    alternativas: ["Presidente da República", "Congresso Nacional", "Senado Federal", "Câmara dos Deputados"],
    explicacao: "Os ministros de Estado são auxiliares do Presidente, que os nomeia e exonera sem precisar de aprovação do Congresso (diferentemente de ministros do STF, por exemplo).",
    fonte: "CF/88, arts. 76 e 84, I",
  },
  {
    id: "q037", tema: "processo-legislativo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Em qual casa legislativa começa a tramitação de um projeto de lei de iniciativa do Presidente da República?",
    alternativas: ["Câmara dos Deputados", "Senado Federal", "Congresso Nacional", "Supremo Tribunal Federal"],
    explicacao: "Os projetos de iniciativa do Presidente, do STF, dos tribunais superiores e dos cidadãos começam pela Câmara dos Deputados. O Senado atua como casa revisora.",
    fonte: "CF/88, art. 64",
  },
  {
    id: "q038", tema: "executivo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem decreta o estado de defesa, para preservar a ordem pública ou a paz social em locais restritos?",
    alternativas: ["Presidente da República", "Congresso Nacional", "Supremo Tribunal Federal", "Ministro da Defesa"],
    explicacao: "O Presidente decreta o estado de defesa, depois de ouvir os Conselhos da República e de Defesa Nacional. O Congresso analisa o decreto em até 10 dias e pode rejeitá-lo por maioria absoluta.",
    fonte: "CF/88, art. 136",
  },
  {
    id: "q039", tema: "cargos", nivel: "federal", tipo: "atribuicao",
    pergunta: "Qual cargo representa os estados e o Distrito Federal no Congresso Nacional, com três ocupantes por unidade da Federação?",
    alternativas: ["Senador", "Deputado Federal", "Governador", "Deputado Estadual"],
    explicacao: "O Senado Federal é a casa dos estados e do DF, com três senadores por unidade da Federação, todos com o mesmo peso independente da população.",
    fonte: "CF/88, art. 46",
  },
  {
    id: "q040", tema: "cargos", nivel: "federal", tipo: "atribuicao",
    pergunta: "Qual cargo representa o povo no Congresso Nacional, em número proporcional à população de cada estado?",
    alternativas: ["Deputado Federal", "Senador", "Deputado Estadual", "Vereador"],
    explicacao: "A Câmara dos Deputados é composta por representantes do povo, com número proporcional à população, respeitados o mínimo de 8 e o máximo de 70 por estado.",
    fonte: "CF/88, art. 45",
  },
  {
    id: "q041", tema: "processo-legislativo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem pode elaborar uma lei delegada?",
    alternativas: ["Presidente da República", "Ministro de Estado", "Supremo Tribunal Federal", "Presidente da Câmara dos Deputados"],
    explicacao: "A lei delegada é elaborada pelo Presidente da República, mediante delegação do Congresso Nacional, por resolução que fixa o conteúdo e os termos do exercício.",
    fonte: "CF/88, art. 68",
  },
  {
    id: "q042", tema: "cargos", nivel: "estadual", tipo: "atribuicao",
    pergunta: "Quem nomeia o Procurador-Geral de Justiça, chefe do Ministério Público de um estado?",
    alternativas: ["Governador", "Assembleia Legislativa", "Presidente do Tribunal de Justiça", "Procurador-Geral da República"],
    explicacao: "O Governador nomeia o Procurador-Geral de Justiça escolhido dentre os nomes de uma lista tríplice formada pelos integrantes da carreira, para mandato de dois anos.",
    fonte: "CF/88, art. 128, § 3º",
  },
  {
    id: "q043", tema: "cargos", nivel: "estadual", tipo: "atribuicao",
    pergunta: "Quem fixa o subsídio dos deputados estaduais?",
    alternativas: ["Assembleia Legislativa", "Governador", "Congresso Nacional", "Tribunal de Justiça"],
    explicacao: "A própria Assembleia Legislativa fixa o subsídio dos deputados estaduais, limitado a 75% do subsídio dos deputados federais.",
    fonte: "CF/88, art. 27, § 2º",
  },
  {
    id: "q044", tema: "executivo", nivel: "estadual", tipo: "atribuicao",
    pergunta: "Quem decreta a intervenção do estado em um município?",
    alternativas: ["Governador", "Assembleia Legislativa", "Presidente da República", "Tribunal de Justiça"],
    explicacao: "A intervenção estadual em municípios é excepcional, só ocorre nos casos previstos na Constituição (como não prestar contas ou não aplicar o mínimo exigido em ensino e saúde) e é decretada pelo Governador.",
    fonte: "CF/88, arts. 35 e 36",
  },
  {
    id: "q045", tema: "seguranca", nivel: "estadual", tipo: "atribuicao",
    pergunta: "A quem estão subordinadas a Polícia Militar e a Polícia Civil de um estado?",
    alternativas: ["Governador", "Prefeito", "Presidente da República", "Ministro da Justiça"],
    explicacao: "As polícias civis, as polícias militares e os corpos de bombeiros militares são subordinados aos Governadores. A Polícia Federal, ao contrário, é órgão da União.",
    fonte: "CF/88, art. 144, § 6º",
  },
  {
    id: "q046", tema: "processo-legislativo", nivel: "estadual", tipo: "atribuicao",
    pergunta: "Quem aprecia o veto do Governador a um projeto aprovado no estado e decide mantê-lo ou derrubá-lo?",
    alternativas: ["Assembleia Legislativa", "Congresso Nacional", "Tribunal de Justiça", "Tribunal de Contas"],
    explicacao: "Por simetria com o modelo federal, o veto é apreciado pela própria Assembleia Legislativa, que pode derrubá-lo pelo voto da maioria absoluta dos deputados, conforme a Constituição estadual.",
    fonte: "CF/88, art. 66, § 4º (por simetria)",
  },
  {
    id: "q047", tema: "controle", nivel: "estadual", tipo: "atribuicao",
    pergunta: "Quem julga as contas anuais do Governador?",
    alternativas: ["Assembleia Legislativa", "Tribunal de Contas", "Tribunal de Justiça", "Congresso Nacional"],
    explicacao: "Como no nível federal, o Tribunal de Contas do Estado emite um parecer prévio e quem julga as contas do chefe do Executivo é o Poder Legislativo, aqui a Assembleia Legislativa.",
    fonte: "CF/88, arts. 71, I, e 75 (por simetria)",
  },
  {
    id: "q048", tema: "educacao", nivel: "estadual", tipo: "atribuicao",
    pergunta: "Quem administra, prioritariamente, as escolas públicas de ensino médio?",
    alternativas: ["Governador", "Prefeito", "Presidente da República", "Ministro da Educação"],
    explicacao: "Os estados e o DF atuam prioritariamente no ensino fundamental e médio. Os municípios cuidam da educação infantil e do ensino fundamental, e a União organiza o sistema federal e apoia os demais.",
    fonte: "CF/88, art. 211, §§ 2º a 4º",
  },
  {
    id: "q049", tema: "educacao", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem é o responsável prioritário pelas creches e pré-escolas públicas?",
    alternativas: ["Prefeito", "Governador", "Presidente da República", "Ministro da Educação"],
    explicacao: "Os municípios atuam prioritariamente na educação infantil (creche e pré-escola) e no ensino fundamental, com apoio técnico e financeiro da União e do estado.",
    fonte: "CF/88, arts. 30, VI, e 211, § 2º",
  },
  {
    id: "q050", tema: "servicos", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem organiza e presta, direta ou indiretamente, o transporte coletivo urbano de uma cidade?",
    alternativas: ["Prefeito", "Governador", "Presidente da República", "Câmara Municipal"],
    explicacao: "O transporte coletivo urbano é serviço público de interesse local, de caráter essencial, a cargo do município, prestado diretamente ou por concessão ou permissão.",
    fonte: "CF/88, art. 30, V",
  },
  {
    id: "q051", tema: "servicos", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem é responsável pela coleta de lixo e pela limpeza urbana?",
    alternativas: ["Prefeito", "Governador", "Presidente da República", "Assembleia Legislativa"],
    explicacao: "Limpeza urbana e manejo de resíduos são serviços públicos de interesse local, de competência municipal, prestados direta ou indiretamente (por concessão ou contrato).",
    fonte: "CF/88, art. 30, V; Lei 11.445/2007",
  },
  {
    id: "q052", tema: "servicos", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem concede o alvará de funcionamento de um comércio local?",
    alternativas: ["Prefeito", "Governador", "Câmara Municipal", "Presidente da República"],
    explicacao: "O alvará é um ato de poder de polícia administrativa sobre assuntos de interesse local e uso do solo urbano. Ele é concedido pela Prefeitura, órgão do Executivo municipal.",
    fonte: "CF/88, art. 30, I e VIII",
  },
  {
    id: "q053", tema: "cargos", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem fixa o subsídio do Prefeito, do Vice-Prefeito e dos secretários municipais?",
    alternativas: ["Câmara Municipal", "Tribunal de Justiça", "Tribunal de Contas", "Governador"],
    explicacao: "O subsídio do chefe do Executivo municipal, do vice e dos secretários é fixado por lei de iniciativa da Câmara Municipal, para a legislatura seguinte.",
    fonte: "CF/88, art. 29, V",
  },
  {
    id: "q054", tema: "controle", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem pode cassar o mandato do Prefeito por infração político-administrativa?",
    alternativas: ["Câmara Municipal", "Tribunal de Contas", "Governador", "Tribunal de Justiça"],
    explicacao: "O Prefeito é julgado pela Câmara Municipal nas infrações político-administrativas e perde o mandato por 2/3 dos vereadores, com contraditório e ampla defesa. Por crimes comuns, responde perante o Tribunal de Justiça.",
    fonte: "Decreto-Lei 201/1967, arts. 4º e 5º",
  },
  {
    id: "q055", tema: "orcamento", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem aprova a lei que altera o Imposto de Renda?",
    alternativas: ["Congresso Nacional", "Ministro da Fazenda", "Assembleia Legislativa", "Presidente da República (por decreto)"],
    explicacao: "O Imposto de Renda é federal e só pode ser criado ou alterado por lei, aprovada pelo Congresso Nacional e sancionada pelo Presidente. Decreto e portaria não criam nem aumentam tributo.",
    fonte: "CF/88, arts. 150, I, e 153, III",
  },
  {
    id: "q056", tema: "competencias", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem tem competência privativa para legislar sobre direito penal?",
    alternativas: ["Congresso Nacional", "Assembleia Legislativa", "Câmara Municipal", "Supremo Tribunal Federal"],
    explicacao: "Direito penal, civil, processual, eleitoral e do trabalho são de competência privativa da União, ou seja, de lei federal. Estados e municípios não criam crimes.",
    fonte: "CF/88, art. 22, I",
  },
  {
    id: "q057", tema: "saude", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem é o principal responsável pelo atendimento básico de saúde, como os postos de saúde de bairro?",
    alternativas: ["Prefeito", "Governador", "Presidente da República", "Ministro da Saúde"],
    explicacao: "O SUS é descentralizado: o município presta os serviços de atendimento básico à saúde da população local, com cooperação técnica e financeira da União e do estado.",
    fonte: "CF/88, arts. 30, VII, e 198",
  },
  {
    id: "q058", tema: "cargos", nivel: "estadual", tipo: "atribuicao",
    pergunta: "Qual destes cargos exige idade mínima de 30 anos para o candidato?",
    alternativas: ["Governador", "Prefeito", "Deputado Federal", "Vereador"],
    explicacao: "Presidente, Vice e Senador exigem 35 anos; Governador e Vice-Governador, 30; deputado federal, estadual ou distrital, prefeito e vice-prefeito, 21; vereador, 18.",
    fonte: "CF/88, art. 14, § 3º, VI",
  },
  {
    id: "q059", tema: "cargos", nivel: "federal", tipo: "atribuicao",
    pergunta: "Qual destes cargos exige idade mínima de 35 anos para o candidato?",
    alternativas: ["Senador", "Governador", "Deputado Federal", "Prefeito"],
    explicacao: "Presidente, Vice-Presidente e Senador exigem 35 anos. Governador exige 30; deputado federal e prefeito, 21; vereador, 18.",
    fonte: "CF/88, art. 14, § 3º, VI",
  },
  {
    id: "q060", tema: "cargos", nivel: "federal", tipo: "atribuicao",
    pergunta: "Qual cargo é eleito junto com exatamente dois suplentes?",
    alternativas: ["Senador", "Deputado Federal", "Governador", "Vereador"],
    explicacao: "Cada senador é eleito com dois suplentes. Deputados e vereadores têm suplentes definidos pela ordem de votação dos candidatos do partido ou federação.",
    fonte: "CF/88, art. 46, § 3º",
  },
  {
    id: "q061", tema: "orcamento", nivel: "estadual", tipo: "atribuicao",
    pergunta: "Quem aprova a lei orçamentária anual de um estado?",
    alternativas: ["Assembleia Legislativa", "Governador", "Tribunal de Contas", "Congresso Nacional"],
    explicacao: "O Governador elabora e envia o projeto, a Assembleia Legislativa discute, emenda e aprova, e o Governador sanciona.",
    fonte: "CF/88, arts. 165 e 166 (por simetria)",
  },
  {
    id: "q062", tema: "orcamento", nivel: "estadual", tipo: "atribuicao",
    pergunta: "Quem aprova a lei que cria ou altera o IPVA?",
    alternativas: ["Assembleia Legislativa", "Câmara Municipal", "Congresso Nacional", "Governador (por decreto)"],
    explicacao: "O IPVA é imposto estadual. Criar ou aumentar tributo exige lei, que no estado é aprovada pela Assembleia Legislativa.",
    fonte: "CF/88, arts. 150, I, e 155, III",
  },
  {
    id: "q063", tema: "orcamento", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem aprova a lei que cria a contribuição para o custeio da iluminação pública?",
    alternativas: ["Câmara Municipal", "Assembleia Legislativa", "Congresso Nacional", "Prefeito (por decreto)"],
    explicacao: "A contribuição para o custeio do serviço de iluminação pública é instituída pelos municípios e pelo DF, por meio de lei aprovada pela Câmara Municipal.",
    fonte: "CF/88, art. 149-A",
  },
  {
    id: "q064", tema: "executivo", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem decreta situação de emergência em um município atingido por enchentes?",
    alternativas: ["Prefeito", "Governador", "Presidente da República", "Câmara Municipal"],
    explicacao: "O chefe do Executivo do município atingido decreta a situação de emergência ou o estado de calamidade pública. O reconhecimento pelo governo estadual ou federal e o repasse de recursos vêm em seguida, a pedido do município.",
    fonte: "Lei 12.608/2012 (Política Nacional de Proteção e Defesa Civil)",
  },
  {
    id: "q065", tema: "controle", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem decide a perda do mandato de um deputado federal por quebra de decoro parlamentar?",
    alternativas: ["Câmara dos Deputados", "Supremo Tribunal Federal", "Senado Federal", "Tribunal Superior Eleitoral"],
    explicacao: "A perda do mandato por quebra de decoro é decidida pela própria Câmara dos Deputados, por maioria absoluta, com ampla defesa. Na condenação criminal definitiva, também cabe à Câmara declarar a perda.",
    fonte: "CF/88, art. 55, II e §§ 2º e 3º",
  },
  {
    id: "q066", tema: "processo-legislativo", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem aprova uma lei de anistia?",
    alternativas: ["Congresso Nacional", "Presidente da República", "Supremo Tribunal Federal", "Senado Federal"],
    explicacao: "Anistia é concedida por lei, aprovada pelo Congresso Nacional e sancionada pelo Presidente. Não confundir com indulto, que é ato individual do Presidente.",
    fonte: "CF/88, art. 48, VIII",
  },
  {
    id: "q067", tema: "cargos", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem fixa o número de vereadores de um município?",
    alternativas: ["Câmara Municipal", "Prefeito", "Tribunal Superior Eleitoral", "Assembleia Legislativa"],
    explicacao: "O número de vereadores é fixado na Lei Orgânica, votada pela Câmara Municipal, proporcional à população do município e dentro dos limites mínimo (9) e máximo (55) da Constituição.",
    fonte: "CF/88, art. 29, IV",
  },
  {
    id: "q068", tema: "processo-legislativo", nivel: "estadual", tipo: "atribuicao",
    pergunta: "Quem cria um novo município?",
    alternativas: ["Assembleia Legislativa", "Congresso Nacional", "Governador", "Tribunal Superior Eleitoral"],
    explicacao: "A criação de município é feita por lei estadual, dentro do período definido em lei complementar federal, depois de estudos de viabilidade e de consulta prévia, por plebiscito, às populações envolvidas.",
    fonte: "CF/88, art. 18, § 4º",
  },
  {
    id: "q069", tema: "habitacao", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem declara, por decreto, a utilidade pública de um imóvel para desapropriação por um município?",
    alternativas: ["Prefeito", "Câmara Municipal", "Governador", "Tribunal de Justiça"],
    explicacao: "A declaração de utilidade pública é feita por decreto do chefe do Executivo, no município o Prefeito. O Legislativo pode tomar a iniciativa, mas os atos necessários ficam com o Executivo.",
    fonte: "Decreto-Lei 3.365/1941, arts. 6º e 8º",
  },
  {
    id: "q070", tema: "processo-legislativo", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem tem iniciativa exclusiva para propor lei que cria cargos no Executivo municipal?",
    alternativas: ["Prefeito", "Vereador", "Câmara Municipal", "Governador"],
    explicacao: "A criação de cargos, funções e empregos na administração direta é de iniciativa privativa do chefe do Executivo. Um vereador não pode propor esse tipo de projeto.",
    fonte: "CF/88, art. 61, § 1º, II, a (por simetria)",
  },
  {
    id: "q071", tema: "orcamento", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem envia à Câmara Municipal o projeto da lei orçamentária anual do município?",
    alternativas: ["Prefeito", "Vereador", "Tribunal de Contas", "Governador"],
    explicacao: "A iniciativa das leis orçamentárias é do chefe do Executivo. A Câmara Municipal discute, emenda e aprova, e o Prefeito sanciona.",
    fonte: "CF/88, art. 165 (por simetria)",
  },
  {
    id: "q072", tema: "economia", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem nomeia o Presidente do Banco Central?",
    alternativas: ["Presidente da República", "Senado Federal", "Ministro da Fazenda", "Conselho Monetário Nacional"],
    explicacao: "O Presidente da República nomeia o Presidente e os diretores do Banco Central depois de aprovados pelo Senado. O mandato é de 4 anos, não coincidente com o do Presidente da República.",
    fonte: "CF/88, art. 84, XIV; Lei Complementar 179/2021",
  },
  {
    id: "q073", tema: "controle", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem recebe a denúncia por crime de responsabilidade contra o Presidente da República e decide se ela segue adiante?",
    alternativas: ["Presidente da Câmara dos Deputados", "Presidente do Senado Federal", "Procurador-Geral da República", "Presidente do STF"],
    explicacao: "A denúncia é apresentada à Câmara, e o Presidente da Câmara decide se a recebe e a encaminha a uma comissão especial. Só depois vêm a votação em plenário (2/3) e o julgamento pelo Senado.",
    fonte: "Lei 1.079/1950, arts. 14 e 19; Regimento Interno da Câmara, art. 218",
  },
  {
    id: "q074", tema: "controle", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem pode derrubar o veto do Prefeito a um projeto aprovado pelos vereadores?",
    alternativas: ["Câmara Municipal", "Governador", "Tribunal de Contas", "Tribunal de Justiça"],
    explicacao: "O veto retorna à Câmara Municipal, que pode derrubá-lo, nos termos da Lei Orgânica (em geral, por maioria absoluta dos vereadores). Isso segue o modelo federal.",
    fonte: "CF/88, art. 66, § 4º (por simetria)",
  },

  // ---------- Lote 2: atribuições gerais (resposta NÃO eletiva) ----------
  {
    id: "n001", tema: "justica", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem julga uma ação direta de inconstitucionalidade contra uma lei federal?",
    alternativas: ["Supremo Tribunal Federal", "Congresso Nacional", "Superior Tribunal de Justiça", "Presidente da República"],
    explicacao: "O STF é o guardião da Constituição e julga originalmente as ações diretas de inconstitucionalidade de leis ou atos normativos federais ou estaduais. Seus ministros são nomeados pelo Presidente, após aprovação do Senado, e não eleitos pelo voto.",
    fonte: "CF/88, art. 102, I, a",
  },
  {
    id: "n002", tema: "justica", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem preside a sessão do Senado que julga o Presidente da República por crime de responsabilidade?",
    alternativas: ["Presidente do Supremo Tribunal Federal", "Presidente do Senado Federal", "Vice-Presidente da República", "Presidente da Câmara dos Deputados"],
    explicacao: "Nesse julgamento, o Senado é presidido pelo Presidente do STF, que só conduz o processo. A condenação só sai por 2/3 dos votos dos senadores.",
    fonte: "CF/88, art. 52, parágrafo único",
  },
  {
    id: "n003", tema: "justica", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem tem o poder privativo de promover a ação penal pública?",
    alternativas: ["Ministério Público", "Polícia Civil", "Juiz de Direito", "Defensoria Pública"],
    explicacao: "A ação penal pública é promovida privativamente pelo Ministério Público (promotores e procuradores), que não é eleito: os membros entram por concurso. A polícia investiga, e o juiz julga.",
    fonte: "CF/88, art. 129, I",
  },
  {
    id: "n004", tema: "justica", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem representa a União, judicial e extrajudicialmente?",
    alternativas: ["Advogado-Geral da União", "Procurador-Geral da República", "Ministro da Justiça", "Presidente do STF"],
    explicacao: "A Advocacia-Geral da União, chefiada pelo Advogado-Geral da União (cargo de livre nomeação pelo Presidente), representa a União em juízo e presta consultoria jurídica ao Executivo.",
    fonte: "CF/88, art. 131",
  },
  {
    id: "n005", tema: "economia", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem define a taxa básica de juros (Selic)?",
    alternativas: ["Copom", "Congresso Nacional", "Ministro da Fazenda", "Presidente da República"],
    explicacao: "A meta da Selic é definida a cada reunião pelo Copom (Comitê de Política Monetária) do Banco Central, formado pelo presidente e pelos diretores da instituição, que não são eleitos. A meta de inflação é fixada pelo Conselho Monetário Nacional.",
    fonte: "Banco Central do Brasil (Copom); Lei Complementar 179/2021",
  },
  {
    id: "n006", tema: "justica", nivel: "municipal", tipo: "atribuicao",
    pergunta: "Quem julga o Prefeito acusado de crime comum?",
    alternativas: ["Tribunal de Justiça", "Câmara Municipal", "Supremo Tribunal Federal", "Tribunal de Contas"],
    explicacao: "O Prefeito tem foro por prerrogativa de função e é julgado pelo Tribunal de Justiça do estado, composto por desembargadores. Já a cassação por infração político-administrativa cabe à Câmara.",
    fonte: "CF/88, art. 29, X",
  },
  {
    id: "n007", tema: "justica", nivel: "estadual", tipo: "atribuicao",
    pergunta: "Quem julga o Governador acusado de crime comum?",
    alternativas: ["Superior Tribunal de Justiça", "Supremo Tribunal Federal", "Tribunal de Justiça", "Assembleia Legislativa"],
    explicacao: "Os Governadores respondem por crimes comuns perante o STJ. Por crime de responsabilidade, o julgamento é feito por tribunal especial previsto na lei e na Constituição estadual.",
    fonte: "CF/88, art. 105, I, a",
  },
  {
    id: "n008", tema: "justica", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem julga os pedidos de registro de candidatura à Presidência da República?",
    alternativas: ["Tribunal Superior Eleitoral", "Supremo Tribunal Federal", "Congresso Nacional", "Presidente da República"],
    explicacao: "O registro de candidatos à Presidência e à Vice-Presidência é julgado originalmente pelo TSE, formado por ministros do STF, do STJ e juristas nomeados pelo Presidente.",
    fonte: "Código Eleitoral (Lei 4.737/1965), art. 22, I, a; CF/88, art. 121",
  },
  {
    id: "n009", tema: "justica", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem oferece a denúncia contra o Presidente da República por crime comum perante o STF?",
    alternativas: ["Procurador-Geral da República", "Advogado-Geral da União", "Presidente da Câmara dos Deputados", "Presidente do Senado Federal"],
    explicacao: "Nos processos perante o STF, o titular da ação penal é o Procurador-Geral da República. A Câmara dos Deputados precisa autorizar, por 2/3, o prosseguimento do processo contra o Presidente.",
    fonte: "CF/88, arts. 102, I, b, 129, I, e 86; Lei 8.038/1990",
  },
  {
    id: "n010", tema: "justica", nivel: "federal", tipo: "atribuicao",
    pergunta: "Quem fiscaliza a atuação administrativa e financeira do Poder Judiciário e o cumprimento dos deveres funcionais dos juízes?",
    alternativas: ["Conselho Nacional de Justiça", "Conselho Nacional do Ministério Público", "Congresso Nacional", "Supremo Tribunal Federal"],
    explicacao: "Essa é a função do CNJ, órgão de controle do Judiciário formado por 15 conselheiros, entre magistrados, membros do MP, advogados e cidadãos, presidido pelo Presidente do STF.",
    fonte: "CF/88, art. 103-B, § 4º",
  },

  // ---------- Casos reais ----------
  {
    id: "r001", tema: "saude", nivel: "estadual", tipo: "real", data_referencia: "2026-07-06",
    pergunta: "Em São Paulo, bares e restaurantes não podem mais oferecer molhos em bisnagas coletivas (os condimentos devem ser servidos em embalagens individuais). Quem editou essa regra?",
    alternativas: [
      "Nenhum cargo eletivo: foi uma portaria de um órgão técnico (CVS)",
      "Governador do estado",
      "Assembleia Legislativa",
      "Prefeito da capital",
    ],
    explicacao: "A regra é a Portaria CVS nº 3, publicada no Diário Oficial do Estado em 6/7/2026 pelo Centro de Vigilância Sanitária, órgão técnico ligado à Secretaria de Estado da Saúde, com prazo de 90 dias e vigor a partir de 4/10/2026. Não foi lei votada por deputados nem decreto do Governador: muita regra do dia a dia vem de órgãos técnicos, e não de cargos eletivos.",
    fonte: "Itatiaia (reportagem sobre a Portaria CVS nº 3/2026)",
    url: "https://www.itatiaia.com.br/brasil/sudeste/sp/bisnagas-com-molhos-serao-proibidas-em-estabelecimentos-de-sao-paulo/",
  },
  {
    id: "r002", tema: "habitacao", nivel: "municipal", tipo: "real", data_referencia: "2026-04-23",
    pergunta: "Em abril de 2026, quem sancionou a lei que criou a Política Municipal de Habitação de Interesse Social de Vitória da Conquista (BA)?",
    alternativas: ["Prefeito", "Governador da Bahia", "Presidente da República", "Câmara Municipal"],
    explicacao: "A prefeita Sheila Lemos sancionou a Lei nº 2.098/2026 em 23/4/2026, que também cria o Fundo Municipal de Habitação de Interesse Social. A Câmara aprova o projeto antes, mas a sanção é ato do chefe do Executivo.",
    fonte: "Prefeitura de Vitória da Conquista",
    url: "https://www.pmvc.ba.gov.br/prefeitura-sanciona-lei-que-cria-politica-municipal-de-habitacao-de-interesse-social-e-cria-fundo-para-ampliar-acesso-a-moradia/",
  },
  {
    id: "r003", tema: "orcamento", nivel: "federal", tipo: "real", data_referencia: "2026-01-14",
    pergunta: "Em janeiro de 2026, quem sancionou, com vetos a cerca de R$ 400 milhões em emendas parlamentares, a Lei Orçamentária Anual de 2026 (Lei 15.346/2026)?",
    alternativas: ["Presidente da República", "Presidente do Congresso Nacional", "Ministro do Planejamento", "Presidente do STF"],
    explicacao: "O Presidente Lula sancionou a LOA 2026 em 14/1/2026 e vetou dois dispositivos. O Congresso aprovou o texto em dezembro de 2025; a sanção e o veto são do Presidente.",
    fonte: "Agência Câmara de Notícias",
    url: "https://www.camara.leg.br/noticias/1238564-orcamento-2026-e-sancionado-com-veto-a-r-400-milhoes-em-emendas/",
  },
  {
    id: "r004", tema: "orcamento", nivel: "federal", tipo: "real", data_referencia: "2026-01-14",
    pergunta: "Os vetos do Presidente à Lei Orçamentária de 2026 ainda precisam ser analisados. Quem decide se eles são mantidos ou derrubados?",
    alternativas: ["Congresso Nacional", "Presidente da República", "Supremo Tribunal Federal", "Tribunal de Contas da União"],
    explicacao: "Vetos são apreciados pelo Congresso Nacional em sessão conjunta de deputados e senadores, e para derrubá-los é preciso maioria absoluta nas duas casas.",
    fonte: "Agência Câmara de Notícias; CF/88, art. 66, § 4º",
    url: "https://www.camara.leg.br/noticias/1238564-orcamento-2026-e-sancionado-com-veto-a-r-400-milhoes-em-emendas/",
  },
  {
    id: "r005", tema: "processo-legislativo", nivel: "federal", tipo: "real", data_referencia: "2026-02-25",
    pergunta: "Em fevereiro de 2026, quem sancionou a Lei 15.352, que alterou a LGPD e criou a Agência Nacional de Proteção de Dados?",
    alternativas: ["Presidente da República", "Presidente da Câmara dos Deputados", "Ministro da Justiça", "Presidente do Senado"],
    explicacao: "A lei foi sancionada pelo Presidente da República e publicada no Diário Oficial da União em 25/2/2026.",
    fonte: "Planalto (notícia sobre a sanção da lei)",
    url: "https://www.gov.br/planalto/pt-br/acompanhe-o-planalto/noticias/2026/02/presidente-lula-sanciona-lei-que-cria-a-agencia-nacional-de-protecao-de-dados",
    revisar: true,
  },
  {
    id: "r006", tema: "controle", nivel: "federal", tipo: "real", data_referencia: "2026-06-10",
    pergunta: "Em junho de 2026, quem aprovou com ressalvas o parecer prévio sobre as contas de 2025 do governo federal?",
    alternativas: ["Tribunal de Contas da União", "Congresso Nacional", "Supremo Tribunal Federal", "Presidente da República"],
    explicacao: "Em sessão extraordinária de 10/6/2026, o plenário do TCU, com relatoria do ministro Benjamin Zymler, aprovou com ressalvas o parecer prévio sobre as contas de 2025. Os ministros do TCU não são eleitos. O julgamento final das contas cabe ao Congresso Nacional.",
    fonte: "O Tempo (reportagem sobre o parecer do TCU)",
    url: "https://www.otempo.com.br/politica/2026/6/18/tcu-aprova-com-ressalvas-as-contas-de-2025-do-governo-federal",
  },
  {
    id: "r007", tema: "executivo", nivel: "municipal", tipo: "real", data_referencia: "2026-07-13",
    pergunta: "Em julho de 2026, a capital fluminense proibiu a publicidade de plataformas de apostas (bets) em espaços públicos, pelo Decreto Rio nº 58.274/2026. Quem edita decretos municipais como esse?",
    alternativas: ["Prefeito", "Câmara Municipal", "Governador", "Presidente da República"],
    explicacao: "Decreto é ato do chefe do Executivo municipal e não passa pela Câmara. O decreto foi publicado em 13/7/2026 e, segundo a reportagem, foi apresentado pelo prefeito da cidade. Houve prazo de 10 dias sem multas para a retirada do material.",
    fonte: "Congresso em Foco",
    url: "https://www.congressoemfoco.com.br/amp/noticia/120430/prefeitura-do-rio-proibe-publicidade-de-bets-em-espacos-publicos",
  },
  {
    id: "r008", tema: "processo-legislativo", nivel: "federal", tipo: "real", data_referencia: "2026-09-03",
    pergunta: "Quem editou a Medida Provisória 1.357/2026, que acabou com a 'taxa das blusinhas' e perdia a validade em 8 de setembro de 2026?",
    alternativas: ["Presidente da República", "Câmara dos Deputados", "Senado Federal", "Ministro da Fazenda"],
    explicacao: "Medida provisória é ato exclusivo do Presidente da República e vale por 60 dias, prorrogáveis por mais 60, enquanto o Congresso a vota. A Câmara aprovou o texto em 3/9/2026 e ele seguiu ao Senado.",
    fonte: "Exame; CF/88, art. 62",
    url: "https://exame.com/brasil/camara-aprova-mp-que-acaba-com-a-taxa-das-blusinhas-texto-vai-ao-senado/",
  },
  {
    id: "r009", tema: "habitacao", nivel: "federal", tipo: "real", data_referencia: "2026-01-12",
    pergunta: "A Lei 15.343/2026 permite o uso gratuito de imóveis ociosos da Previdência para ações como saúde, educação e moradia. Que cargo apresentou o projeto original (PL 3758/2024)?",
    alternativas: ["Deputado Federal", "Senador", "Presidente da República", "Ministro da Previdência"],
    explicacao: "O projeto foi de autoria do deputado federal Romero Rodrigues e foi aprovado pela Câmara em agosto de 2025. O Presidente da República apenas o sancionou, com publicação em 12/1/2026.",
    fonte: "Agência Câmara de Notícias",
    url: "https://www.camara.leg.br/noticias/1237761-imoveis-ociosos-da-previdencia-poderao-ser-cedidos-para-fins-sociais/",
  },
];
